<div>
<div class="page-heading"><div><p class="eyebrow">Produksi {{ $type }}</p><h1 class="page-title">Catat produksi baru</h1><p class="page-description">Bahan dalam proses dipisahkan dari stok produk siap jual.</p></div><a href="{{ route('batches.index',['type'=>$type]) }}" class="btn">Kembali ke daftar</a></div><x-feedback/>
<form wire:submit="save" class="grid items-start gap-6 lg:grid-cols-[1fr_320px]"><section class="panel space-y-5 p-6"><h2 class="text-sm font-semibold">Identitas & penerimaan bahan</h2><div class="grid gap-4 sm:grid-cols-2"><label class="field">Nomor batch<input class="input" wire:model="batch_number" required></label><label class="field">Nama batch<input class="input" wire:model="name"></label></div><label class="field">Tanggal penerimaan<input class="input" type="date" wire:model="start_date" required></label>
@if($type === 'Beras')<label class="field">Asal bahan / pemasok<input class="input" wire:model="origin" placeholder="Nama pemasok atau asal gabah"></label>@else
<label class="field">Cari batch asal<input class="input" wire:model.live.debounce.300ms="sourceSearch" placeholder="Nomor atau nama batch..."></label><label class="field">Batch gabah asal<select class="input" wire:model.live="source_batch_id" required><option value="">Pilih batch selesai</option>@foreach($sources as $source)<option value="{{ $source->id }}">{{ $source->batch_number }} · {{ number_format($type === 'Dedek' ? $source->dedek_weight - ($source->used_dedek ?? 0) : $source->pupuk_weight - ($source->used_pupuk ?? 0),3,',','.') }} kg tersedia</option>@endforeach</select></label>
@if($selectedSource)<div class="rounded-lg bg-[#ecfaf5] p-4 text-sm">Sisa tersedia: <strong>{{ number_format($type === 'Dedek' ? $selectedSource->dedek_weight - ($selectedSource->used_dedek ?? 0) : $selectedSource->pupuk_weight - ($selectedSource->used_pupuk ?? 0),3,',','.') }} kg</strong><p class="mt-2 text-xs text-brand-textGray">Bahan langsung dialokasikan saat batch disimpan dan tidak dapat digunakan lagi oleh batch lain.</p></div>@endif
@endif
<label class="field">{{ $type === 'Beras' ? 'Berat awal gabah (kg)' : 'Berat sisa bahan yang dipakai (kg)' }}<input class="input" wire:model.live.debounce.300ms="raw_material_weight" inputmode="decimal" required></label>
@if($type === 'Beras')<label class="field">Harga beli / kg (Rp)<input class="input" wire:model.live.debounce.300ms="purchase_price" inputmode="decimal"></label><div class="rounded-lg bg-[#ecfaf5] p-4 text-sm">Total pembelian: <strong>Rp {{ number_format((float)str_replace(',', '.',(string)$raw_material_weight) * (float)str_replace(',', '.',(string)$purchase_price),2,',','.') }}</strong></div><label class="flex items-center gap-2 text-xs"><input type="checkbox" wire:model.live="purchase_paid">Pembelian sudah dibayar</label>@if($purchase_paid)<label class="field">Tanggal pembayaran<input type="date" class="input" wire:model="paid_date" required></label>@endif @endif
<label class="field">Catatan<textarea class="input" wire:model="notes" rows="3"></textarea></label></section>
<aside class="panel space-y-5 p-6"><h2 class="text-sm font-semibold">Tahapan kerja</h2><ol class="space-y-4">@foreach(\App\ProductionWorkflow::stages($type) as $stage)<li class="flex items-center gap-3 text-xs"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#ecfaf5] text-[#13866e]">{{ $loop->iteration }}</span>{{ $stage }}</li>@endforeach</ol><p class="border-t border-[#e5ebf1] pt-4 text-xs leading-6 text-brand-textGray">Produksi dimulai dari tahap Belum Diproses. Hasil baru masuk stok setelah proses selesai dan dikonfirmasi.</p><button class="btn btn-primary w-full" wire:loading.attr="disabled">Simpan & lihat proses</button></aside></form>
</div>
