<div>
<div class="page-heading"><div><p class="eyebrow">Detail produksi {{ $batch->type }}</p><h1 class="page-title">{{ $batch->batch_number }}</h1><p class="page-description">{{ $batch->name ?: 'Catatan produksi' }} · {{ $batch->origin ?: 'Asal belum diisi' }} · {{ $batch->start_date }}</p></div><a class="btn" href="{{ route('batches.index',['type'=>$batch->type]) }}">Kembali ke daftar produksi</a></div><x-feedback/>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat label="Berat bahan awal" :value="\App\Decimal::display($batch->raw_material_weight, 3).' kg'" icon="box"/><x-stat label="Total biaya tercatat" :value="'Rp '.number_format($totalCost,0,',','.')"/><x-stat label="Tahap aktif" :value="$batch->current_stage" icon="leaf"/><x-stat label="Status hasil" :value="$batch->outputs->count() ? 'Sudah masuk stok' : 'Belum masuk stok'" icon="check"/></div>
<section class="panel mb-6 p-5"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach(\App\ProductionWorkflow::stages($batch->type) as $stage)
@php $active = $stage === $batch->current_stage; $completed = $batch->stages->contains('stage_name',$stage) || ($stage === 'Selesai' && $batch->status === 'Selesai'); @endphp
<div @class(['flex items-center gap-3 rounded-xl border p-4','border-[#f67113] bg-[#eef4ff]'=>$active,'border-[#eaeef2] bg-white'=>!$active])><span @class(['flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs','bg-brand-primary text-white'=>$completed,'bg-[#d8e2ff] text-[#747780]'=>!$completed])>@if($completed)<x-icon name="check"/>@else{{ $loop->iteration }}@endif</span><div><p class="text-xs font-semibold">{{ $stage }}</p><p class="mt-1 text-[10px] text-brand-textGray">{{ $active ? 'Tahap saat ini' : ($completed ? 'Selesai' : 'Terkunci') }}</p></div></div>@endforeach</div></section>
<div class="grid items-start gap-6 xl:grid-cols-[1.5fr_1fr]">
<section class="panel p-6">
@if($batch->status !== 'Selesai')
<h2 class="mb-5 text-base font-semibold">{{ $batch->current_stage }}</h2><form wire:submit="addStage" class="space-y-5"><label class="field">Tanggal tahap<input class="input" type="date" wire:model="stage_start_date" required></label>
@if($batch->current_stage !== 'Belum Diproses')
<label class="field">{{ $batch->current_stage === 'Pengeringan' ? 'Hasil berat kering' : 'Berat hasil akhir' }} (kg)<input class="input" wire:model.live.debounce.300ms="stage_weight_after" inputmode="decimal" required></label>
@if($batch->current_stage === 'Pemisahan')<div class="grid gap-4 sm:grid-cols-2"><label class="field">Sisa untuk dedek (kg)<input class="input" wire:model.live="dedek_weight" inputmode="decimal"></label><label class="field">Sisa untuk merang/pupuk (kg)<input class="input" wire:model.live="pupuk_weight" inputmode="decimal"></label></div><p class="text-xs text-brand-textGray">Bahan masuk {{ \App\Decimal::display($batch->dry_weight, 3) }} kg · Susut / tidak terpakai {{ \App\Decimal::display((float)$batch->dry_weight - (float)str_replace(',', '.',(string)$stage_weight_after) - (float)str_replace(',', '.',(string)$dedek_weight) - (float)str_replace(',', '.',(string)$pupuk_weight), 3) }} kg</p>@endif
@if($batch->type === 'Pupuk')<div class="space-y-3"><div class="flex items-center justify-between"><h3 class="text-sm font-semibold">Bahan campuran</h3><button type="button" class="btn" wire:click="addMixture"><x-icon name="plus"/>Bahan</button></div>@foreach($mixtures as $i=>$mixture)<div wire:key="mixture-{{ $i }}" class="space-y-3 rounded-lg border border-[#eaeef2] p-4"><label class="field">Nama bahan<input class="input" wire:model="mixtures.{{ $i }}.name"></label><div class="grid grid-cols-2 gap-3"><label class="field">Berat kg<input class="input" wire:model="mixtures.{{ $i }}.weight" inputmode="decimal"></label><label class="field">Biaya Rp<input class="input" wire:model="mixtures.{{ $i }}.cost" inputmode="decimal"></label></div><div class="flex justify-between"><label class="flex items-center gap-2 text-xs"><input type="checkbox" wire:model="mixtures.{{ $i }}.paid">Sudah dibayar</label><button type="button" class="text-xs text-red-700" wire:click="removeMixture({{ $i }})">Hapus bahan</button></div></div>@endforeach</div>@endif
@endif
<label class="field">Catatan tahap<textarea class="input" wire:model="stage_notes" rows="3"></textarea></label><p class="text-xs leading-6 text-brand-textGray">Catat semua biaya proses sebelum menyelesaikan produksi. Tahap yang disimpan tidak dapat diulang atau dilewati.</p><button class="btn btn-primary" wire:loading.attr="disabled" data-confirm="Simpan hasil tahap dan lanjutkan proses?">{{ $batch->current_stage === 'Belum Diproses' ? 'Mulai proses' : 'Simpan & lanjutkan tahap' }}</button></form>
@else
<h2 class="text-base font-semibold">Produksi selesai</h2><p class="mt-2 text-sm text-brand-textGray">Hasil timbang aktual: <strong class="text-brand-textDark">{{ \App\Decimal::display($batch->result_weight, 3) }} kg {{ $batch->type }}</strong></p>
@if($batch->outputs->count())<div class="mt-5 rounded-xl bg-[#eef4ff] p-5 text-sm text-brand-primary"><x-icon name="check" class="mr-2"/>Sudah masuk ke {{ $batch->outputs->first()->product->name }}.</div>
@elseif($batch->result_weight <= 0)<p class="mt-5 rounded-xl bg-[#f6fafe] p-4 text-sm text-brand-textGray">Produksi ditutup tanpa hasil. Tidak ada stok yang ditambahkan.</p>
@else
@if(!$batch->cost_finalized_at)<p class="mt-5 rounded-xl bg-amber-50 p-4 text-xs leading-6 text-amber-800">Atur pembagian biaya di panel Biaya produksi. Seluruh biaya harus dibagikan sebelum hasil masuk stok atau sisa bahan digunakan.</p>@endif
<div class="mt-5 space-y-4"><label class="field">Cari produk tujuan<input class="input" wire:model.live.debounce.300ms="productSearch" placeholder="Nama produk..."></label><label class="field">Produk tujuan<select class="input" wire:model.live="output_product_id"><option value="">Pilih produk aktif</option>@foreach($outputProducts as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select></label>
@if($selectedProduct)<div class="rounded-lg bg-[#eef4ff] p-4 text-xs leading-6"><p>Batch: {{ $batch->batch_number }} · {{ $batch->type }} · {{ \App\Decimal::display($batch->result_weight, 3) }} kg</p><p>Stok sebelum: {{ \App\Decimal::display($selectedProduct->stock_kg, 3) }} kg</p><p>Stok sesudah: {{ \App\Decimal::display($selectedProduct->stock_kg + $batch->result_weight, 3) }} kg</p>@if($batch->cost_finalized_at)<p>Modal/kg sesudah: Rp {{ \App\Decimal::display(($selectedProduct->inventory_value + ($batch->cost_allocation[$batch->type] ?? 0)) / ($selectedProduct->stock_kg + $batch->result_weight), 2) }}</p>@endif</div>@endif
<button class="btn btn-primary" wire:click="addOutput" wire:loading.attr="disabled" data-confirm="Tambahkan seluruh hasil timbang ke stok produk ini?" @disabled(!$batch->cost_finalized_at || !$output_product_id)>Konfirmasi masuk stok</button>
<details class="border-t border-[#eaeef2] pt-4 text-xs"><summary class="font-medium text-brand-primary">Produk belum ada? Tambah produk baru</summary><div class="mt-4 space-y-3"><label class="field">Nama produk<input class="input" wire:model="new_product_name"></label><label class="field">Harga jual / kg<input class="input" wire:model="new_product_price" inputmode="decimal"></label><button class="btn" wire:click="createProduct">Buat produk dengan stok nol</button></div></details></div>
@endif
@endif
</section>
<div class="space-y-6">
<section class="panel p-5"><h2 class="mb-4 text-sm font-semibold">Biaya produksi</h2>
@if($batch->inherited_cost > 0)<p class="mb-3 text-xs text-brand-textGray">Modal bahan dari batch asal: Rp {{ \App\Decimal::display($batch->inherited_cost, 2) }}. Tidak membuat kas keluar baru.</p>@endif
@if($batch->status === 'Selesai' && !$batch->cost_finalized_at)
<form wire:submit="finalizeCosts" class="mb-5 space-y-3 rounded-lg border border-[#eaeef2] p-4"><h3 class="text-xs font-semibold">Pembagian biaya hasil</h3>
@foreach($batch->type === 'Beras' ? ['Beras','Dedek','Pupuk'] : [$batch->type] as $outputType)<label class="field">Modal {{ $outputType }} (Rp)<input class="input" wire:model.live.debounce.300ms="allocation.{{ $outputType }}" inputmode="decimal"></label>@endforeach
<p class="text-xs text-brand-textGray">Sisa pembagian: Rp {{ \App\Decimal::display((float)$totalCost - array_sum(array_map(fn($value)=>(float)str_replace(',', '.',(string)$value),$allocation)), 2) }}</p><p class="text-[10px] leading-5 text-brand-textGray">Tentukan nominal sesuai hasil. Setelah disimpan, pembagian biaya akan dikunci dan tidak membuat kas baru.</p><button class="btn btn-primary" wire:loading.attr="disabled" data-confirm="Simpan seluruh pembagian biaya? Nilainya akan dikunci.">Simpan pembagian</button></form>
@elseif($batch->cost_finalized_at)<div class="mb-4 rounded-lg bg-[#eef4ff] p-3 text-xs"><p class="font-medium">Modal sudah difinalkan</p>@foreach($batch->cost_allocation ?? [] as $outputType=>$allocatedCost)<p class="mt-1 text-brand-textGray">{{ $outputType }}: Rp {{ \App\Decimal::display($allocatedCost, 2) }}</p>@endforeach</div>@endif<div class="divide-y divide-[#eaeef2]">@forelse($batch->costs as $cost)<div class="flex items-center justify-between gap-3 py-3"><div><p class="text-xs font-medium">{{ $cost->name }}</p><p class="mt-1 text-[11px] text-brand-textGray">Rp {{ \App\Decimal::display($cost->amount, 2) }} · {{ $cost->category }}</p></div>@if($cost->paid_at)<span class="badge">Dibayar {{ $cost->paid_at }}</span>@else<button class="btn" wire:click="payCost({{ $cost->id }})" data-confirm="Konfirmasi biaya ini dibayar lunas pada tanggal pembayaran yang dipilih?">Bayar lunas</button>@endif</div>@empty<p class="py-3 text-xs text-brand-textGray">Belum ada biaya tambahan.</p>@endforelse</div>
<label class="field mt-3">Tanggal pencatatan / pembayaran<input class="input" type="date" wire:model="cost_date"></label>
@if(!$batch->cost_finalized_at)<details class="mt-4 text-xs"><summary class="font-medium text-brand-primary">Tambah komponen biaya</summary><form wire:submit="saveCost" class="mt-4 space-y-3"><label class="field">Nama biaya<input class="input" wire:model="cost_name" required></label><label class="field">Kategori<select class="input" wire:model="cost_category"><option>Biaya Pengolahan</option><option>Pembelian Bahan</option></select></label><label class="field">Nominal Rp<input class="input" wire:model="cost_amount" inputmode="decimal" required></label><label class="flex items-center gap-2"><input type="checkbox" wire:model="cost_paid">Sudah dibayar</label><button class="btn" wire:loading.attr="disabled">Simpan biaya</button></form></details>@endif
</section>
@if($batch->type === 'Beras' && $batch->status === 'Selesai')<section class="panel p-5"><h2 class="mb-4 text-sm font-semibold">Sisa bahan lanjutan</h2>@foreach(['Dedek'=>'dedek_weight','Pupuk'=>'pupuk_weight'] as $type=>$field)@php $allocated = $batch->children->where('type',$type)->sum('raw_material_weight'); @endphp<div class="mb-4 border-b border-[#eaeef2] pb-4"><h3 class="text-xs font-semibold">{{ $type }}</h3><div class="mt-2 grid grid-cols-3 gap-2 text-[10px] text-brand-textGray"><p>Total<br><strong class="text-xs text-brand-textDark">{{ \App\Decimal::display($batch->$field, 3) }} kg</strong></p><p>Dialokasikan<br><strong class="text-xs text-brand-textDark">{{ \App\Decimal::display($allocated, 3) }} kg</strong></p><p>Tersedia<br><strong class="text-xs text-brand-primary">{{ \App\Decimal::display($batch->$field-$allocated, 3) }} kg</strong></p></div></div>@endforeach</section>@endif
</div>
</div>
<section class="panel mt-6 p-6"><h2 class="mb-5 text-sm font-semibold">Riwayat tahapan</h2><div class="grid gap-4 md:grid-cols-3">@forelse($batch->stages as $stage)<article class="border-l-2 border-[#f67113] pl-4"><h3 class="text-sm font-medium">{{ $stage->stage_name }}</h3><p class="mt-1 text-[11px] text-brand-textGray">{{ $stage->start_date }} → {{ $stage->end_date }}</p>@if($stage->weight_after !== null)<p class="mt-2 text-sm">{{ \App\Decimal::display($stage->weight_after, 3) }} kg</p>@endif<p class="mt-2 text-xs text-brand-textGray">{{ $stage->notes ?: 'Tanpa catatan' }}</p></article>@empty<p class="text-xs text-brand-textGray">Proses belum dimulai.</p>@endforelse</div>
@if($batch->mixtures)<h3 class="mb-3 mt-6 text-sm font-semibold">Campuran tercatat</h3>@foreach($batch->mixtures as $mixture)<p class="text-xs leading-6">{{ $mixture['name'] }} · {{ \App\Decimal::display($mixture['weight'], 3) }} kg · Rp {{ \App\Decimal::display($mixture['cost'], 2) }}</p>@endforeach @endif
<details class="mt-6 border-t border-[#eaeef2] pt-5 text-xs"><summary class="font-medium text-brand-primary">Edit nama dan catatan batch</summary><form wire:submit="saveMetadata" class="mt-4 space-y-3"><label class="field">Nama batch<input class="input" wire:model="batch_name"></label><label class="field">Catatan<textarea class="input" wire:model="batch_notes"></textarea></label><button class="btn">Simpan perubahan</button></form></details>
</section>
</div>
