<div>
<div class="page-heading"><div><p class="eyebrow">Keuangan</p><h1 class="page-title">{{ $direction === 'Pengeluaran' ? 'Pengeluaran' : 'Pemasukan' }}</h1><p class="page-description">Catatan kas berdasarkan tanggal uang diterima atau dibayarkan.</p></div><a class="btn" href="{{ route('cash.index',['direction'=>$direction === 'Pengeluaran' ? 'Pemasukan' : 'Pengeluaran']) }}">Buka {{ $direction === 'Pengeluaran' ? 'pemasukan' : 'pengeluaran' }} <x-icon name="arrow"/></a></div><x-feedback/>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
@if($direction === 'Pengeluaran')<x-stat label="Total pengeluaran" :value="'Rp '.number_format($totalPengeluaran,0,',','.')"/><x-stat label="Pembelian bahan & produk" :value="'Rp '.number_format($pembelianBahan,0,',','.')"/><x-stat label="Biaya pengolahan" :value="'Rp '.number_format($biayaPengolahan,0,',','.')"/><x-stat label="Gaji serta operasional lainnya" :value="'Rp '.number_format($gajiOperasional,0,',','.')"/>
@else<x-stat label="Total pemasukan" :value="'Rp '.number_format($totalPemasukan,0,',','.')"/><x-stat label="Penerimaan penjualan langsung" :value="'Rp '.number_format($penjualanLangsung,0,',','.')"/><x-stat label="Penerimaan piutang" :value="'Rp '.number_format($penerimaanPiutang,0,',','.')"/><x-stat label="Pemasukan lainnya" :value="'Rp '.number_format($pemasukanLainnya,0,',','.')"/>@endif
</div>
<div class="grid items-start gap-6 xl:grid-cols-[310px_1fr]">
<section class="panel p-5"><h2 class="mb-5 text-sm font-semibold">{{ $entryId ? 'Edit catatan manual' : 'Catat '.strtolower($direction) }}</h2><form wire:submit="save" class="space-y-4"><label class="field">Nama transaksi<input class="input" wire:model="name" required></label><label class="field">Tanggal<input type="date" class="input" wire:model="entry_date" required></label><label class="field">Kategori<input class="input" wire:model="category" list="cash-categories" required><datalist id="cash-categories">@foreach($direction === 'Pemasukan' ? ['Modal Pemilik','Pemasukan Lainnya'] : ['Pembelian Bahan','Biaya Pengolahan','Operasional Lainnya'] as $value)<option value="{{ $value }}">@endforeach</datalist></label><label class="field">Nominal (Rp)<input class="input" wire:model="amount" inputmode="decimal" required></label>
@if($type === 'Pengeluaran')<label class="field">Klasifikasi<select class="input" wire:model.live="classification"><option>Operasional</option><option value="Produksi">Biaya Produksi</option></select></label>@if($classification === 'Produksi')<label class="field">Batch tujuan<select class="input" wire:model="production_batch_id" required><option value="">Pilih batch</option>@foreach($batches as $batch)<option value="{{ $batch->id }}">{{ $batch->batch_number }}</option>@endforeach</select></label>@endif @endif
<label class="field">Keterangan<textarea class="input" wire:model="description" rows="2"></textarea></label><button class="btn btn-primary w-full" wire:loading.attr="disabled">Simpan catatan</button>@if($entryId)<button class="btn w-full" type="button" wire:click="resetForm">Batal edit</button>@endif</form></section>
<section class="panel min-w-0 overflow-hidden"><div class="filters"><label class="field flex-1 min-w-36">Pencarian<input class="input" wire:model.live.debounce.300ms="search" placeholder="Nama / referensi..."></label><label class="field">Dari<input type="date" class="input" wire:model.live="from"></label><label class="field">Sampai<input type="date" class="input" wire:model.live="to"></label><label class="field">Kategori<select class="input" wire:model.live="categoryFilter"><option value="">Semua</option>@foreach($categories as $value)<option>{{ $value }}</option>@endforeach</select></label><label class="field">Sumber<select class="input" wire:model.live="source"><option value="">Semua</option><option value="manual">Manual</option><option value="automatic">Otomatis</option><option value="pos">POS</option><option value="receivable">Pembayaran Piutang</option><option value="payroll">Gaji</option><option value="production">Biaya batch</option><option value="product">Pembelian produk</option></select></label></div>
<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Transaksi</th><th>Tanggal</th><th>Nominal</th><th>Sumber</th><th>Aksi</th></tr></thead><tbody>
@forelse($entries as $entry)<tr wire:key="cash-{{ $entry->id }}"><td class="max-w-60"><p class="font-medium">{{ $entry->name ?: $entry->description ?: $entry->category }}</p><p class="mt-1 text-[11px] text-brand-textGray">{{ $entry->category }} · {{ $entry->classification }}</p></td><td class="whitespace-nowrap">{{ \Carbon\Carbon::parse($entry->entry_date)->format('d/m/Y') }}</td><td class="whitespace-nowrap font-semibold">Rp {{ \App\Decimal::display($entry->amount, 2) }}</td><td><span class="badge">{{ $entry->reference_type ? ($entry->reference_type === \App\Models\Payroll::class ? 'Gaji' : ($entry->reference_type === \App\Models\Product::class ? 'Pembelian produk' : ($entry->category === 'Penjualan Langsung' ? 'POS' : ($entry->category === 'Penerimaan Piutang' ? 'Pembayaran Piutang' : 'Produksi')))) : 'Manual' }}</span></td><td>
@if(!$entry->reference_type)<div class="flex gap-2"><button class="btn" wire:click="edit({{ $entry->id }})">Edit</button><button class="btn btn-danger" wire:click="delete({{ $entry->id }})" data-confirm="Hapus catatan kas ini?" @disabled(in_array($entry->id,$linkedEntries)) title="Pengeluaran yang terhubung ke batch tidak dapat dihapus">Hapus</button></div>
@elseif($entry->reference_type === \App\Models\Payment::class)<a class="btn" href="{{ route('sales.index',['detail'=>$paymentSales[$entry->reference_id] ?? null]) }}">Buka transaksi</a>
@elseif($entry->reference_type === \App\Models\Sale::class)<a class="btn" href="{{ route('sales.index',['detail'=>$entry->reference_id]) }}">Buka transaksi</a>
@elseif($entry->reference_type === \App\Models\Payroll::class)<a class="btn" href="{{ route('payrolls.index') }}">Buka gaji</a>
@elseif($entry->reference_type === \App\Models\Product::class)<a class="btn" href="{{ route('products.form',$entry->reference_id) }}">Buka produk</a>
@elseif($entry->production_batch_id)<a class="btn" href="{{ route('batches.show',$entry->production_batch_id) }}">Buka batch</a>@endif</td></tr>
@empty<tr><td colspan="5"><div class="empty-state">Belum ada catatan kas yang sesuai filter.</div></td></tr>@endforelse</tbody></table></div><div class="p-5">{{ $entries->links() }}</div></section>
</div></div>
