<div>
<div class="page-heading"><div><p class="eyebrow">Persediaan</p><h1 class="page-title">Produk & stok</h1><p class="page-description">Pantau persediaan, harga jual, dan modal produk Anda.</p></div><a href="{{ route('products.form') }}" class="btn btn-primary"><x-icon name="plus"/>Tambah produk</a></div>
<x-feedback/>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat label="Total harga produk" :value="'Rp '.number_format($totalHargaProduk,0,',','.')" note="Nilai persediaan pada harga jual" icon="box"/><x-stat label="Total harga modal" :value="'Rp '.number_format($totalHargaModal,0,',','.')" note="Nilai modal persediaan"/><x-stat label="Jumlah produk" :value="$jumlahProduk" note="Sesuai pencarian dan filter" icon="grid"/><x-stat label="Produk stok menipis" :value="$produkStokMenipis" note="Produk aktif pada batas minimum" icon="box"/></div>
@if($adjustId)<section class="panel mb-6 p-5"><h2 class="mb-4 text-sm font-semibold">Penyesuaian stok aktual</h2><form wire:submit="saveAdjustment" class="flex flex-wrap items-end gap-4"><div class="text-sm"><p class="text-xs text-brand-textGray">Stok sebelumnya</p><p class="mt-2 font-semibold">{{ number_format($previousStock,3,',','.') }} kg</p></div><label class="field">Stok akhir hasil timbang (kg)<input wire:model.live.debounce.300ms="actualStock" class="input" inputmode="decimal"></label><p class="py-2 text-xs">Selisih: {{ number_format((float)str_replace(',', '.',(string)$actualStock) - (float)$previousStock,3,',','.') }} kg</p><button class="btn btn-primary" wire:confirm="Ubah stok ke jumlah aktual ini? Tidak ada transaksi kas baru.">Konfirmasi penyesuaian</button><button type="button" wire:click="$set('adjustId', null)" class="btn">Batal</button></form></section>@endif
<section class="panel overflow-hidden"><div class="filters"><label class="field min-w-44 flex-1">Cari produk<input wire:model.live.debounce.300ms="search" class="input" placeholder="Nama atau kode produk..."></label><label class="field">Kategori<select wire:model.live="category" class="input"><option value="">Semua kategori</option>@foreach(['Beras','Dedek','Pupuk','Lainnya','Bahan Baku'] as $value)<option>{{ $value }}</option>@endforeach</select></label><label class="field">Status<select wire:model.live="status" class="input"><option value="">Aktif & nonaktif</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></label><label class="flex min-h-10 items-center gap-2 text-xs"><input wire:model.live="lowStock" type="checkbox">Stok menipis</label></div>
<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Produk</th><th>Kategori</th><th>Stok kg</th><th>Minimum kg</th><th>Modal/kg</th><th>Harga jual/kg</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($products as $product)<tr wire:key="product-{{ $product->id }}"><td><a href="{{ route('products.form',$product->id) }}" class="font-semibold">{{ $product->name }}</a><p class="mt-1 text-[10px] text-brand-textGray">{{ $product->code }}</p></td><td>{{ $product->type }}</td><td><span @class(['font-semibold','text-amber-700'=>$product->is_active && $product->stock_kg <= $product->stock_minimum])>{{ number_format($product->stock_kg,3,',','.') }}</span></td><td class="text-brand-textGray">{{ number_format($product->stock_minimum,3,',','.') }}</td><td class="whitespace-nowrap">Rp {{ number_format($product->cogs_per_kg,2,',','.') }}</td><td class="whitespace-nowrap font-medium">Rp {{ number_format($product->selling_price,2,',','.') }}</td><td><button wire:click="toggle({{ $product->id }})" wire:confirm="Ubah status produk?" class="badge">{{ $product->is_active ? 'Aktif' : 'Nonaktif' }}</button></td><td><div class="flex gap-2"><a class="btn" href="{{ route('products.form',$product->id) }}">Detail</a><button class="btn" wire:click="adjust({{ $product->id }})">Stok</button><button class="btn btn-danger" wire:click="delete({{ $product->id }})" wire:confirm="Hapus produk ini?" @disabled($product->sale_items_count + $product->outputs_count + $product->batches_count > 0) title="{{ $product->sale_items_count + $product->outputs_count + $product->batches_count > 0 ? 'Dipakai dalam penjualan/produksi. Nonaktifkan bila tidak digunakan.' : 'Hapus produk' }}">Hapus</button></div></td></tr>
@empty<tr><td colspan="8"><div class="empty-state">Belum ada produk yang sesuai pencarian.</div></td></tr>@endforelse
</tbody></table></div><div class="flex flex-wrap items-center justify-between gap-3 p-5"><label class="field">Baris<select wire:model.live="perPage" class="input"><option>10</option><option>25</option><option>50</option></select></label>{{ $products->links() }}</div></section>
</div>
