<div>
<div class="page-heading"><div><p class="eyebrow">Persediaan</p><h1 class="page-title">Produk & stok</h1><p class="page-description">Pantau persediaan, harga jual, dan modal produk Anda.</p></div><a href="{{ route('products.form') }}" class="btn btn-primary"><x-icon name="plus"/>Tambah produk</a></div>
<x-feedback/>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat label="Total harga produk" :value="'Rp '.number_format($totalHargaProduk,0,',','.')" note="Nilai persediaan pada harga jual" icon="box"/><x-stat label="Total harga modal" :value="'Rp '.number_format($totalHargaModal,0,',','.')" note="Nilai modal persediaan"/><x-stat label="Jumlah produk" :value="$jumlahProduk" note="Sesuai pencarian dan filter" icon="grid"/><x-stat label="Produk stok menipis" :value="$produkStokMenipis" note="Produk aktif pada batas minimum" icon="box"/></div>
@if($adjustId)
<div class="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto p-4" wire:key="stock-purchase-{{ $purchaseKey }}" x-data @keydown.escape.window="$wire.cancelAdjustment()" x-init="$nextTick(() => $refs.stockInput.focus())">
<button type="button" class="fixed inset-0 bg-slate-950/40" wire:click="cancelAdjustment" aria-label="Tutup stok masuk"></button>
<section role="dialog" aria-modal="true" aria-labelledby="stock-purchase-title" class="panel relative max-h-[90dvh] w-full max-w-lg overflow-y-auto p-6">
<div class="mb-5 flex items-start justify-between gap-4"><div><p class="eyebrow">Pembelian produk</p><h2 id="stock-purchase-title" class="text-xl font-bold">Tambah stok masuk</h2><p class="mt-1 text-sm text-brand-textGray">{{ $stockProductName }}</p></div><button type="button" class="btn" wire:click="cancelAdjustment" aria-label="Tutup">×</button></div>
<x-feedback/>
<div class="mb-5 grid grid-cols-2 gap-4 rounded-xl bg-brand-bgMain p-4 text-sm"><div><p class="text-xs text-brand-textGray">Stok saat ini</p><p class="mt-1 font-semibold">{{ \App\Decimal::display((float)$previousStock, 3) }} kg</p></div><div><p class="text-xs text-brand-textGray">Modal rata-rata saat ini</p><p class="mt-1 font-semibold">Rp {{ \App\Decimal::display((float)$previousCost, 2) }} / kg</p></div></div>
<form wire:submit="saveAdjustment" class="space-y-5">
<label class="field">Jumlah stok masuk (kg)<input x-ref="stockInput" wire:model.live.debounce.300ms="incomingStock" class="input" inputmode="decimal" placeholder="Contoh: 100" required></label>
<label class="field">Total belanja stok (Rp, opsional)<input wire:model.live.debounce.300ms="purchaseTotal" class="input" inputmode="decimal" placeholder="Total biaya pembelian"><span class="text-xs font-normal leading-5 text-brand-textGray">Jika kosong, dihitung dari stok masuk × modal per kg saat ini. Isi total belanja jika harga pembelian berubah. Isi 0 untuk stok tanpa biaya.</span></label>
@if($purchasePreview)<div class="space-y-3 rounded-xl bg-[#eef4ff] p-4 text-sm" aria-live="polite"><div class="flex justify-between gap-3"><span>Pengeluaran pembelian</span><strong>Rp {{ \App\Decimal::display((float)$purchasePreview['total'], 2) }}</strong></div><div class="flex justify-between gap-3"><span>Stok setelah pembelian</span><strong>{{ \App\Decimal::display((float)$purchasePreview['stock'], 3) }} kg</strong></div><div class="flex justify-between gap-3 border-t border-blue-100 pt-3"><span>Modal rata-rata baru / kg</span><strong>Rp {{ \App\Decimal::display((float)$purchasePreview['average'], 2) }}</strong></div></div>@endif
<p class="text-xs leading-5 text-brand-textGray">Pembelian ini menambah stok dan mencatat pengeluaran pada tanggal hari ini. Modal rata-rata dihitung dari total modal stok lama ditambah total belanja baru, dibagi seluruh stok yang tersedia.</p>
<div class="flex justify-end gap-3"><button type="button" wire:click="cancelAdjustment" class="btn">Batal</button><button class="btn btn-primary" wire:loading.attr="disabled" wire:target="saveAdjustment">Simpan stok masuk</button></div>
</form></section></div>
@endif
<section class="panel overflow-hidden"><div class="filters"><label class="field min-w-44 flex-1">Cari produk<input wire:model.live.debounce.300ms="search" class="input" placeholder="Nama atau kode produk..."></label><label class="field">Kategori<select wire:model.live="category" class="input"><option value="">Semua kategori</option>@foreach(['Beras','Dedek','Pupuk','Lainnya','Bahan Baku'] as $value)<option>{{ $value }}</option>@endforeach</select></label><label class="field">Status<select wire:model.live="status" class="input"><option value="">Aktif & nonaktif</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></label><label class="flex min-h-10 items-center gap-2 text-xs"><input wire:model.live="lowStock" type="checkbox">Stok menipis</label></div>
<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Produk</th><th>Tanggal</th><th>Kategori</th><th>Stok kg</th><th>Minimum kg</th><th>Modal/kg</th><th>Harga jual/kg</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($products as $product)<tr wire:key="product-{{ $product->id }}"><td><a href="{{ route('products.form',$product->id) }}" class="font-semibold">{{ $product->name }}</a><p class="mt-1 text-[10px] text-brand-textGray">{{ $product->code }}</p></td><td class="whitespace-nowrap text-brand-textGray" title="Tanggal produk ditambahkan">{{ $product->created_at?->timezone('Asia/Jakarta')->format('d/m/Y') ?? '-' }}</td><td>{{ $product->type }}</td><td><span @class(['font-semibold','text-amber-700'=>$product->is_active && $product->stock_kg <= $product->stock_minimum])>{{ \App\Decimal::display($product->stock_kg, 3) }}</span></td><td class="text-brand-textGray">{{ \App\Decimal::display($product->stock_minimum, 3) }}</td><td class="whitespace-nowrap">Rp {{ \App\Decimal::display($product->cogs_per_kg, 2) }}</td><td class="whitespace-nowrap font-medium">Rp {{ \App\Decimal::display($product->selling_price, 2) }}</td><td><button wire:click="toggle({{ $product->id }})" data-confirm="Ubah status produk?" class="badge">{{ $product->is_active ? 'Aktif' : 'Nonaktif' }}</button></td><td><div class="flex gap-2"><a class="btn" href="{{ route('products.form',$product->id) }}">Detail</a><button class="btn" wire:click="adjust({{ $product->id }})">Stok</button><button class="btn btn-danger" wire:click="delete({{ $product->id }})" data-confirm="Hapus produk ini?" @disabled($product->sale_items_count + $product->outputs_count + $product->batches_count + $product->cash_entries_count > 0) title="{{ $product->sale_items_count + $product->outputs_count + $product->batches_count + $product->cash_entries_count > 0 ? 'Memiliki riwayat penjualan, produksi, atau pengeluaran. Nonaktifkan bila tidak digunakan.' : 'Hapus produk' }}">Hapus</button></div></td></tr>
@empty<tr><td colspan="9"><div class="empty-state">Belum ada produk yang sesuai pencarian.</div></td></tr>@endforelse
</tbody></table></div><div class="flex flex-wrap items-center justify-between gap-3 p-5"><label class="field">Baris<select wire:model.live="perPage" class="input"><option>10</option><option>25</option><option>50</option></select></label>{{ $products->links() }}</div></section>
</div>
