<div>
<div class="page-heading"><div><p class="eyebrow">Keuangan & tim</p><h1 class="page-title">Pembayaran gaji</h1><p class="page-description">Catat pembayaran karyawan dan pengeluaran kas secara bersamaan.</p></div></div><x-feedback/>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat label="Total gaji dibayar" :value="'Rp '.number_format($totalGajiDibayar,0,',','.')"/><x-stat label="Total gaji harian" :value="'Rp '.number_format($totalGajiHarian,0,',','.')"/><x-stat label="Total gaji bulanan" :value="'Rp '.number_format($totalGajiBulanan,0,',','.')"/><x-stat label="Jumlah karyawan dibayar" :value="$jumlahKaryawanDibayar" note="Karyawan unik dalam hasil filter" icon="users"/></div>
<div class="grid items-start gap-6 xl:grid-cols-[330px_1fr]"><section class="panel p-5"><h2 class="mb-5 text-sm font-semibold">{{ $payrollId ? 'Edit pembayaran' : 'Pembayaran baru' }}</h2><form wire:submit="save" class="space-y-4">
<label class="field">Cari karyawan<input class="input" wire:model.live.debounce.300ms="employeeSearch" placeholder="Nama karyawan..."></label><label class="field">Karyawan<select class="input" wire:model.live="employee_id" required><option value="">Pilih karyawan aktif</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @disabled(!$employee->is_active && !$payrollId)>{{ $employee->name }}{{ !$employee->is_active ? ' (nonaktif)' : '' }}</option>@endforeach</select></label>
<div class="grid grid-cols-2 gap-3"><label class="field">Tanggal bayar<input class="input" type="date" wire:model="payroll_date" required></label><label class="field">Jenis gaji<select class="input" wire:model.live="salary_type"><option>Harian</option><option>Bulanan</option></select></label></div>
<div class="grid grid-cols-2 gap-3"><label class="field">Periode mulai<input class="input" type="date" wire:model="period_start" required></label><label class="field">Periode akhir<input class="input" type="date" wire:model="period_end" required></label></div>
@if($salary_type === 'Harian')<div class="grid grid-cols-2 gap-3"><label class="field">Tarif / hari (Rp)<input class="input" wire:model="daily_rate" inputmode="decimal"></label><label class="field">Hari kerja<input class="input" type="number" wire:model="work_days" min="1" max="366"></label></div><button type="button" wire:click="calculateAmount" class="text-xs font-medium text-brand-primary">Hitung tarif × hari kerja</button>@endif
<label class="field">Nominal final yang dibayar (Rp)<input class="input" wire:model="total_amount" inputmode="decimal" required></label>
<label class="field">Klasifikasi<select class="input" wire:model.live="classification"><option>Operasional</option><option value="Produksi">Biaya Produksi</option></select></label>
@if($classification === 'Produksi')<label class="field">Batch produksi<select class="input" wire:model="production_batch_id" required><option value="">Pilih batch</option>@foreach($batches as $batch)<option value="{{ $batch->id }}">{{ $batch->batch_number }}</option>@endforeach</select></label>@endif
<label class="field">Keterangan<textarea class="input" wire:model="notes" rows="2"></textarea></label>
<label class="flex items-start gap-2 text-[11px] leading-5 text-brand-textGray"><input class="mt-1" type="checkbox" wire:model="confirmSimilar">Saya sudah memeriksa pembayaran dengan periode serupa dan ini pembayaran berbeda.</label>
<button class="btn btn-primary w-full" wire:loading.attr="disabled" wire:confirm="Simpan pembayaran gaji dan pengeluaran kas?">Simpan pembayaran gaji</button>@if($payrollId)<button class="btn w-full" type="button" wire:click="resetForm">Batal edit</button>@endif</form></section>
<section class="panel min-w-0 overflow-hidden"><div class="filters"><label class="field">Tanggal bayar dari<input type="date" class="input" wire:model.live="from"></label><label class="field">Sampai<input type="date" class="input" wire:model.live="to"></label><label class="field">Karyawan<select class="input" wire:model.live="employeeFilter"><option value="">Semua</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@endforeach</select></label><label class="field">Jenis<select class="input" wire:model.live="salaryFilter"><option value="">Semua</option><option>Harian</option><option>Bulanan</option></select></label></div>
<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Karyawan / periode</th><th>Tanggal bayar</th><th>Jenis</th><th>Nominal</th><th>Aksi</th></tr></thead><tbody>
@forelse($payrolls as $payroll)<tr wire:key="payroll-{{ $payroll->id }}"><td><p class="font-medium">{{ $payroll->employee->name }}</p><p class="mt-1 text-[10px] whitespace-nowrap text-brand-textGray">{{ $payroll->period_start }} — {{ $payroll->period_end }}</p></td><td class="whitespace-nowrap">{{ $payroll->payroll_date }}</td><td><span class="badge">{{ $payroll->salary_type ?: 'Data lama' }}</span><p class="mt-1 text-[10px] text-brand-textGray">{{ $payroll->classification }}</p></td><td class="whitespace-nowrap font-semibold">Rp {{ number_format($payroll->total_amount,0,',','.') }}</td><td><div class="flex gap-2"><button class="btn" wire:click="edit({{ $payroll->id }})">Edit</button><button class="btn btn-danger" wire:click="delete({{ $payroll->id }})" wire:confirm="Hapus gaji ini?" @disabled($payroll->payment_status === 'Sudah Dibayar') title="Gaji dibayar terhubung pengeluaran dan tidak dapat dihapus">Hapus</button>@if($payroll->payment_status !== 'Sudah Dibayar')<button class="btn" wire:click="pay({{ $payroll->id }})" wire:confirm="Bayar gaji lama ini?">Bayar</button>@endif</div></td></tr>
@empty<tr><td colspan="5"><div class="empty-state">Belum ada pembayaran gaji yang sesuai filter.</div></td></tr>@endforelse</tbody></table></div><div class="p-5">{{ $payrolls->links() }}</div></section></div>
</div>
