<div x-data="{ cartOpen: false }" @keydown.escape.window="cartOpen = false" class="pb-20 xl:pb-0">
<div class="page-heading"><div><p class="eyebrow">Keuangan & tim</p><h1 class="page-title">Pembayaran gaji</h1><p class="page-description">Pilih karyawan, atur hari kerja, lalu bayar gaji sekaligus.</p></div><a href="{{ route('employees.index') }}" class="btn"><x-icon name="users"/>Daftar karyawan</a></div>
<x-feedback/>
<div class="mb-6 grid gap-4 sm:grid-cols-3"><x-stat label="Total gaji dibayar" :value="'Rp '.number_format($totalGajiDibayar,0,',','.')"/><x-stat label="Gaji harian dibayar" :value="'Rp '.number_format($totalGajiHarian,0,',','.')"/><x-stat label="Karyawan dibayar" :value="$jumlahKaryawanDibayar" note="Sesuai filter riwayat" icon="users"/></div>
@if(!$payrollId)
<div x-show="cartOpen" x-cloak @click="cartOpen = false" class="fixed inset-0 z-30 bg-slate-950/25 xl:hidden"></div>
<button type="button" x-show="!menuOpen" @click="cartOpen = !cartOpen" :aria-expanded="cartOpen" aria-controls="payroll-cart" class="pos-cart-toggle fixed inset-x-0 bottom-0 z-50 flex min-h-14 items-center justify-between bg-brand-primary px-5 py-3 text-sm font-semibold text-white xl:hidden"><span>Keranjang gaji ({{ count($cart) }})</span><svg class="h-5 w-5 transition-transform" :class="cartOpen ? '' : 'rotate-180'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></button>
<div class="mb-6 grid items-start gap-6 xl:grid-cols-[1fr_390px]">
<section class="panel min-w-0 overflow-hidden"><div class="filters"><label class="field flex-1">Cari karyawan<input class="input" wire:model.live.debounce.300ms="employeeSearch" placeholder="Nama atau posisi..."></label><a href="{{ route('employees.index') }}" class="btn"><x-icon name="plus"/>Tambah karyawan</a></div>
<div class="grid grid-cols-2 gap-2.5 p-3 sm:grid-cols-3 xl:grid-cols-3 2xl:grid-cols-4">
@forelse($availableEmployees as $employee)
<button type="button" wire:key="salary-card-{{ $employee->id }}" wire:click="addToCart({{ $employee->id }})" wire:loading.attr="disabled" wire:target="addToCart,checkout" @class(['pos-product-card group p-3 sm:p-3', 'is-selected' => isset($cart[$employee->id])]) aria-label="Pilih {{ $employee->name }} untuk pembayaran gaji">
<span class="mb-2.5 flex items-center justify-between gap-2"><span class="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#eef4ff] text-xs font-bold text-brand-primary">{{ mb_strtoupper(mb_substr($employee->name,0,1)) }}</span><span class="truncate rounded-md bg-brand-bgMain px-2 py-1 text-[9px] font-medium text-brand-textGray">Harian</span></span>
<span class="line-clamp-2 min-h-8 font-heading text-xs font-semibold leading-4">{{ $employee->name }}</span><span class="mt-1 truncate text-[10px] text-[#747780]">{{ $employee->role ?: 'Karyawan' }}</span>
<span class="mt-2.5 flex items-center justify-between gap-1 border-t border-[#eaeef2] pt-2.5"><span class="min-w-0"><strong class="block font-heading text-sm font-bold tracking-tight text-brand-primary">Rp {{ number_format($employee->default_rate,0,',','.') }}</strong><span class="text-[9px] text-brand-textGray">per hari</span></span><span class="pos-product-add flex h-7 w-7 shrink-0 items-center justify-center rounded-lg"><x-icon name="plus" class="h-4 w-4"/></span></span>
</button>
@empty<div class="empty-state col-span-full">Belum ada karyawan aktif dengan gaji harian.<br>Isi gaji per hari di daftar karyawan terlebih dahulu.</div>@endforelse
</div><div class="px-5 pb-5">{{ $availableEmployees->links() }}</div></section>
<section id="payroll-cart" class="panel pos-drawer overflow-hidden" :class="cartOpen ? 'is-open' : 'is-closed'">
<div class="flex shrink-0 items-center justify-between gap-3 border-b border-[#eaeef2] bg-white p-5"><div><h2 class="text-base font-semibold">Keranjang gaji</h2><p class="mt-1 text-[11px] text-brand-textGray">{{ count($cart) }} karyawan dipilih</p></div><button type="button" class="btn btn-danger" wire:click="clearCart" wire:loading.attr="disabled" @disabled(!$cart)>Kosongkan</button></div>
<div class="min-h-0 flex-1 overflow-y-auto overscroll-contain pb-16 xl:pb-0">
<div class="space-y-4 p-5 xl:max-h-80 xl:overflow-y-auto">
@forelse($cart as $id => $item)
<div wire:key="salary-cart-{{ $id }}" class="border-b border-[#eaeef2] pb-4"><div class="flex justify-between gap-2"><p class="text-sm font-semibold">{{ $cartLines[$id]['name'] ?? 'Karyawan tidak ditemukan' }}</p><button type="button" wire:click="removeItem({{ $id }})" aria-label="Hapus karyawan dari keranjang" class="text-brand-textGray"><x-icon name="close"/></button></div><p class="mt-1 text-[11px] text-brand-textGray">Rp {{ number_format($cartLines[$id]['rate'] ?? 0,0,',','.') }} / hari</p><div class="mt-3 flex items-center justify-between gap-3"><label class="flex items-center gap-2 text-xs"><input aria-label="Hari kerja {{ $cartLines[$id]['name'] ?? '' }}" class="input max-w-20" type="number" min="1" max="366" wire:model.live.debounce.300ms="cart.{{ $id }}.days">hari</label><strong class="text-sm">Rp {{ number_format($cartLines[$id]['amount'] ?? 0,0,',','.') }}</strong></div></div>
@empty<div class="empty-state"><x-icon name="users" class="mb-3 h-8 w-8"/><p>Belum ada karyawan dipilih.</p><p class="text-xs">Pilih kartu karyawan untuk memulai.</p></div>@endforelse
</div>
<form wire:submit="checkout" class="space-y-4 border-t border-[#eaeef2] bg-[#f6fafe] p-5">
<x-feedback/>
<div class="flex items-center justify-between text-lg font-semibold"><span>Total gaji</span><span class="text-brand-primary">Rp {{ number_format($cartTotal,0,',','.') }}</span></div>
<label class="field">Tanggal bayar<input class="input" type="date" wire:model="payroll_date" required></label>
<div class="grid grid-cols-2 gap-3"><label class="field">Kerja dari<input class="input" type="date" wire:model.live="period_start" required></label><label class="field">Sampai<input class="input" type="date" wire:model.live="period_end" required></label></div>
<p class="text-[11px] leading-5 text-brand-textGray">Untuk satu hari, gunakan tanggal kerja yang sama. Total setiap karyawan = gaji per hari × hari kerja.</p>
<details><summary class="cursor-pointer text-xs font-medium text-brand-primary">Catatan & biaya produksi</summary><div class="mt-3 space-y-3"><label class="field">Catatan<input class="input" wire:model="notes" placeholder="Catatan pembayaran..."></label><label class="field">Biaya untuk<select class="input" wire:model.live="classification"><option value="Operasional">Operasional</option><option value="Produksi">Produksi</option></select></label>@if($classification === 'Produksi')<label class="field">Produksi tujuan<select class="input" wire:model="production_batch_id"><option value="">Pilih produksi</option>@foreach($batches as $batch)<option value="{{ $batch->id }}">{{ $batch->name ?: $batch->batch_number }}</option>@endforeach</select></label>@endif</div></details>
@if($errors->has('confirmSimilar') || $confirmSimilar)<label class="flex items-start gap-2 text-xs leading-5"><input type="checkbox" wire:model="confirmSimilar" class="mt-1">Saya sudah memeriksa riwayat. Ini pembayaran tambahan untuk periode yang sama.</label>@endif
<button class="btn btn-primary w-full" wire:loading.attr="disabled" wire:target="checkout" @disabled(!$cart) data-confirm="Bayar seluruh gaji di keranjang dan catat ke Pengeluaran?"><x-icon name="check"/><span wire:loading.remove wire:target="checkout">Bayar gaji</span><span wire:loading wire:target="checkout">Menyimpan pembayaran...</span></button>
<p class="text-[10px] leading-5 text-brand-textGray">Pembayaran langsung lunas dan otomatis tercatat di Pengeluaran.</p>
</form></div></section></div>
@endif

@if($payrollId)
<section class="panel p-5"><h2 class="mb-5 text-sm font-semibold">Koreksi pembayaran</h2><form wire:submit="save" class="space-y-4">
<label class="field">Cari karyawan<input class="input" wire:model.live.debounce.300ms="employeeSearch" placeholder="Nama karyawan..."></label><label class="field">Karyawan<select class="input" wire:model.live="employee_id" required><option value="">Pilih karyawan aktif</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @disabled(!$employee->is_active && !$payrollId)>{{ $employee->name }}{{ !$employee->is_active ? ' (nonaktif)' : '' }}</option>@endforeach</select></label>
<div class="grid grid-cols-2 gap-3"><label class="field">Tanggal bayar<input class="input" type="date" wire:model="payroll_date" required></label><label class="field">Jenis gaji<select class="input" wire:model.live="salary_type"><option>Harian</option><option>Bulanan</option></select></label></div>
<div class="grid grid-cols-2 gap-3"><label class="field">Periode mulai<input class="input" type="date" wire:model="period_start" required></label><label class="field">Periode akhir<input class="input" type="date" wire:model="period_end" required></label></div>
@if($salary_type === 'Harian')<div class="grid grid-cols-2 gap-3"><label class="field">Tarif / hari (Rp)<input class="input" wire:model="daily_rate" inputmode="decimal"></label><label class="field">Hari kerja<input class="input" type="number" wire:model="work_days" min="1" max="366"></label></div><button type="button" wire:click="calculateAmount" class="text-xs font-medium text-brand-primary">Hitung tarif × hari kerja</button>@endif
<label class="field">Nominal final yang dibayar (Rp)<input class="input" wire:model="total_amount" inputmode="decimal" required></label>
<label class="field">Klasifikasi<select class="input" wire:model.live="classification"><option>Operasional</option><option value="Produksi">Biaya Produksi</option></select></label>
@if($classification === 'Produksi')<label class="field">Batch produksi<select class="input" wire:model="production_batch_id" required><option value="">Pilih batch</option>@foreach($batches as $batch)<option value="{{ $batch->id }}">{{ $batch->batch_number }}</option>@endforeach</select></label>@endif
<label class="field">Keterangan<textarea class="input" wire:model="notes" rows="2"></textarea></label>
<label class="flex items-start gap-2 text-[11px] leading-5 text-brand-textGray"><input class="mt-1" type="checkbox" wire:model="confirmSimilar">Saya sudah memeriksa pembayaran dengan periode serupa dan ini pembayaran berbeda.</label>
<button class="btn btn-primary w-full" wire:loading.attr="disabled" data-confirm="Simpan pembayaran gaji dan pengeluaran kas?">Simpan pembayaran gaji</button>@if($payrollId)<button class="btn w-full" type="button" wire:click="resetForm">Batal edit</button>@endif</form></section>
@endif
<section class="panel min-w-0 overflow-hidden"><div class="filters"><label class="field">Tanggal bayar dari<input type="date" class="input" wire:model.live="from"></label><label class="field">Sampai<input type="date" class="input" wire:model.live="to"></label><label class="field">Karyawan<select class="input" wire:model.live="employeeFilter"><option value="">Semua</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@endforeach</select></label><label class="field">Jenis<select class="input" wire:model.live="salaryFilter"><option value="">Semua</option><option>Harian</option><option>Bulanan</option></select></label></div>
<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Karyawan / periode</th><th>Tanggal bayar</th><th>Jenis</th><th>Nominal</th><th>Aksi</th></tr></thead><tbody>
@forelse($payrolls as $payroll)<tr wire:key="payroll-{{ $payroll->id }}"><td><p class="font-medium">{{ $payroll->employee->name }}</p><p class="mt-1 text-[10px] whitespace-nowrap text-brand-textGray">{{ \Carbon\Carbon::parse($payroll->period_start)->format('d/m/Y') }} — {{ \Carbon\Carbon::parse($payroll->period_end)->format('d/m/Y') }}</p></td><td class="whitespace-nowrap">{{ \Carbon\Carbon::parse($payroll->payroll_date)->format('d/m/Y') }}</td><td><span class="badge">{{ $payroll->salary_type ?: 'Data lama' }}</span><p class="mt-1 text-[10px] text-brand-textGray">{{ $payroll->classification }}</p></td><td class="whitespace-nowrap font-semibold">Rp {{ number_format($payroll->total_amount,0,',','.') }}</td><td><div class="flex gap-2"><button class="btn" wire:click="edit({{ $payroll->id }})">Edit</button><button class="btn btn-danger" wire:click="delete({{ $payroll->id }})" data-confirm="Hapus gaji ini?" @disabled($payroll->payment_status === 'Sudah Dibayar') title="Gaji dibayar terhubung pengeluaran dan tidak dapat dihapus">Hapus</button>@if($payroll->payment_status !== 'Sudah Dibayar')<button class="btn" wire:click="pay({{ $payroll->id }})" data-confirm="Bayar gaji lama ini?">Bayar</button>@endif</div></td></tr>
@empty<tr><td colspan="5"><div class="empty-state">Belum ada pembayaran gaji yang sesuai filter.</div></td></tr>@endforelse</tbody></table></div><div class="p-5">{{ $payrolls->links() }}</div></section>
</div>
