<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Nota {{ $sale->invoice_number }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body><div class="no-print mx-auto flex max-w-3xl justify-between px-4 pt-6"><a href="{{ route('sales.index', ['detail' => $sale->id]) }}" class="btn">Kembali</a><button onclick="window.print()" class="btn btn-primary">Cetak nota</button></div>
<main class="receipt panel mx-auto my-6 max-w-3xl p-6 sm:p-10"><header class="mb-8 flex flex-wrap justify-between gap-4"><div><p class="eyebrow">Nota penjualan</p><h1 class="text-2xl font-semibold">{{ auth()->user()->store_name }}</h1></div><div class="text-sm"><p class="font-semibold">{{ $sale->invoice_number }}</p><p class="mt-1 text-brand-textGray">{{ $sale->sale_date }}</p></div></header>
<p class="mb-5 text-sm">Pelanggan: <strong>{{ $sale->customer?->name ?? 'Umum' }}</strong></p>
<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Produk</th><th>Kg</th><th>Harga/kg</th><th>Subtotal</th></tr></thead><tbody>@foreach($sale->items as $item)<tr><td>{{ $item->product_name ?? 'Produk #'.$item->product_id }}</td><td>{{ \App\Decimal::display($item->quantity, 3) }}</td><td>{{ \App\Decimal::display($item->price, 2) }}</td><td>{{ \App\Decimal::display($item->subtotal, 2) }}</td></tr>@endforeach</tbody></table></div>
<dl class="ml-auto mt-6 max-w-sm space-y-3 text-sm">@foreach(['Subtotal'=>$sale->subtotal, 'Diskon'=>$sale->discount, 'Total'=>$sale->total, 'Sudah dibayar'=>$sale->paid_amount, 'Sisa tagihan'=>$sale->balance] as $label=>$value)<div class="flex justify-between gap-5"><dt>{{ $label }}</dt><dd class="font-semibold">Rp {{ \App\Decimal::display($value, 2) }}</dd></div>@endforeach</dl>
@if($sale->due_date)<p class="mt-6 text-sm">Jatuh tempo: {{ $sale->due_date }}</p>@endif
@if($sale->notes)<p class="mt-5 text-sm text-brand-textGray">{{ $sale->notes }}</p>@endif
<footer class="mt-10 border-t border-[#eaeef2] pt-5 text-center text-xs text-brand-textGray">Terima kasih telah berbelanja di {{ auth()->user()->store_name }}.</footer></main></body></html>
